language: c
arch:
  - arm32
services:
  - docker
before_install:
  - docker build -t me/image .
script:
  # One of those lines is necessary otherwise travis runs 'rake' by default.
  - true
  - echo "Success"
