language: c
dist: focal
before_install:
  - sudo apt -y install git
  - mkdir raspberrypi && cd raspberrypi
  - git clone git://github.com/raspberrypi/tools.git
  - export PATH=$PATH:$HOME/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
  - export PATH=$PATH:$HOME/raspberrypi/tools/arm-bcm2708-linux-gnueabi/bin
script: arm-linux-gnueabihf-gcc -v
